### ISSUE TITLE
automated tests needed

### ISSUE THREAD

**Issue by WilkAndy** [uw-comphys/opencmp#11]
I think automated tests are mandatory, and i can't find any.  You have tutorial examples - great, a new user can test things are working to some degree, but it wouldn't take much work to build a test suite out of those, so that new users can be confident things are working as planned.  For instance in "tutorial 4", various norms are outputted, but these are different for my computer than are shown at https://opencmp.io/tutorials/tutorial_4.html .   While i'm not too concerned at the differences, it would be much easier and confidence-inspiring if new users could just write
```
python run_all_tests.py
```
and OpenCMP replies back: "all tests passed".  I use the python `unittest`.

**Comment by Alex-Vasile** [comment]
A range on python unit tests are available under `pytests/`. They can be run with `pytest pytests/`.

**NOTE:** At the moment, running them will require adding the main OpenCMP folder to your python path, e.g. running `echo PYPOTHONPATH="path_to_opencmp_main_folder:$PYTHONPATH"` in the terminal first.

The tests are a mixture of testing individual functions and modules, as well as full simulations. As such, they take a non-trivial amount of time to run, about 15 minutes to run on a 4 core, 8 thread, desktop machine.

**Comment by nasserma** [comment]
Following-up on Alex's comment, unit tests using the pytest module were provided and may be run using that module from the top-level of the installation. I have added more detail to the installation guide to clarify this,

https://opencmp.io/getting_started/installation_guide.html
