### ISSUE TITLE
JOSS tutorial 9

### ISSUE THREAD

**Issue by bonh** [uw-comphys/opencmp#21]
Running `python3 visualization`results in 
```
importing NGSolve-6.2.2105
Traceback (most recent call last):
  File "visualization.py", line 8, in <module>
    from opencmp.helpers.ngsolve_ import ngsolve_to_numpy
ImportError: cannot import name 'ngsolve_to_numpy' from 'opencmp.helpers.ngsolve_' (/root/opencmp/opencmp/helpers/ngsolve_.py)
```
I am on branch `publications`, is that wrong?

**Comment by bonh** [comment]
Mhhh, no, I am confused, sry. On `main` I am not able to execute `python3 visualization` as that file is not there?

**Comment by nasserma** [comment]
> Did you fix it? I am asking because it is still not working for me.

We did fix the issue and update the _publications_ branch with the fix, just to confirm, did you reinstall the package before trying again?

**Comment by bonh** [comment]
Don't know what was going on, but now it seems to work. Testing again...

**Comment by bonh** [comment]
Nice work, looks good
