### ISSUE TITLE
I'm kind of pulling my hair out over here in Australia!!    I'm pretty sure i installed and tested the software, but have since got a new computer and am having lots of trouble installing ngsolve.  It's a real beast with the conda version not working, the mac version not working properly with opencmp, and properly testing opencmp being problematic (for me) on windows.

### ISSUE THREAD

**Issue by Alex-Vasile** [uw-comphys/opencmp#23]
__Originally posted by @WilkAndy in https://github.com/openjournals/joss-reviews/issues/3742#issuecomment-1035697198__

**Comment by Alex-Vasile** [comment]
Hi, if you can provide me with some more info on the troubles you're having with the mac version, I can try to help you sort it out

**Comment by nasserma** [comment]
One of us has it working on MacOS, so we should be able to help.

**Comment by nasserma** [comment]
@WilkAndy can you confirm that you are still having installation issues on MacOS? Otherwise we can close this issue,

https://github.com/uw-comphys/opencmp/issues/23
