### ISSUE TITLE
sys.exit() logging produces error

### ISSUE THREAD

**Issue by Alex-Vasile** [uw-comphys/opencmp#41]
If the timestep to be taken falls below the minimum, we write perform some logging and then exit using:
https://github.com/uw-comphys/opencmp/blob/df1ae2f4b992c39577000233fff5e910d4ec79b3/opencmp/solvers/adaptive_transient_solvers/base_adaptive_transient_multistep.py#L87-L89

That line produces the following error when hit:
`TypeError: 'str' object cannot be interpreted as an integer`.

**Comment by nasserma** [comment]
Resolved by commit 2f29723.
