### ISSUE TITLE
JOSS: Add Installation Instructions for NGSolve

### ISSUE THREAD

**Issue by Alex-Vasile** [uw-comphys/opencmp#5]
As per https://github.com/openjournals/joss-reviews/issues/3742#issuecomment-937444021.

**Comment by WilkAndy** [comment]
Prob can just link to https://docu.ngsolve.org/latest/install/install_sources.html and/or https://ngsolve.org/downloads

**Comment by nasserma** [comment]
Please see the updated installation instructions, this change has been made,

https://opencmp.io/getting_started/installation_guide.html
