### ISSUE TITLE
Need to bound nonlinear solver parameter ```alpha``` 

### ISSUE THREAD

**Issue by mptino** [uw-comphys/opencmp#51]
```alpha``` is currently calculated as 
```python
alpha = 0.5 * max(1., x_prev.Norm()) / f.Norm()
```
but this can lead to over-estimations in the magnitude of alpha.

For example, one specific problem initialized ```alpha``` as ```alpha = 4.8```, but the iterations experience severe error oscillation (```low error ``` $\longleftrightarrow$ ```high error```) and fails to converge within reasonable number of iterations.

However, when choosing ```alpha ~ 1.```, we obtain rapid convergence (less than 20 iterations). 

Need to investigate acceptable bounds for ```alpha``` although currently none exist in their implementations in ```scipy/optimize/_nonlin.py```.

**Comment by nasserma** [comment]
Addressed with commit 1913c43.
