### ISSUE TITLE
JOSS: Expand on paper

### ISSUE THREAD

**Issue by Alex-Vasile** [uw-comphys/opencmp#8]
1. code coverage
2. perhaps outline the tutorials
3. a bit more details about the user interface
4. a picture of an example, perhaps explaining why your code/approach is advantageous in terms of usability, accuracy, computational efficiency, etc, compared with other codes. Sometimes it is hard to not denigrate excellent alternative codes when you're doing this, but you needn't go over-the-top: you're just trying to show the reader your code is nice.

per: https://github.com/openjournals/joss-reviews/issues/3742#issuecomment-924368594

Go over 1000 words to address them in more detail within the paper itself, per https://github.com/openjournals/joss-reviews/issues/3742#issuecomment-940430141.

**Comment by nasserma** [comment]
We have address comments 1-3 in our most recent revision. Regarding comment #4, we are confirming with one of the reviewers regarding what example would be best for this additional section.
